language: java
jdk: openjdk11
sudo: false

install: true

branches:
    only:
    - master

before_script: cd neuroph

script:
- mvn compile
- mvn test
- mvn verify

cache:
    directories:
        - "$HOME/.m2/repository"
