#!/usr/bin/env python3

import sys
import fileinput
import os

# take in input (loop required by python but will only run once because one line of input to this hook)
for refs_input in fileinput.input():
    branch_ref = refs_input.split(" ")[2].strip()
    branch_ref_name = branch_ref.split("/")[2].strip()

    branch_ref_valid = branch_ref_name.startswith('feature/') or branch_ref_name.startswith('bugfix/') or branch_ref_name.startswith('hotfix/')

		message = ""

    if branch_ref_valid is False:
        print(message)
        sys.exit(1)

    break

sys.exit(0)